backend:
  name: github
  repo: ochiroma/www.gulpdigital.com # Path to your Github repository
  branch: master # Branch to update (master by default)
  base_url: https://d3846542-413f-11e7-a919-92ebcb.herokuapp.com

media_folder: "img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow

collections: # A list of collections the CMS should be able to edit
  - name: "content" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Content" # Used in the UI, ie.: "New Post"
    folder: "content/home" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Foo", name: "foo", widget: "foo"}
      - {label: "Publish Date", name: "date", widget: "datetime"}